version: '2'
services:
  xserver:
    image: devrt/xserver
    ports:
      - "3000:80"
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspace
      - ~/.gitconfig:/home/developer/.gitconfig
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
    volumes_from:
      - xserver
    depends_on:
      - xserver